#!/usr/bin/env node

var hostname = require("os").hostname();
var url = process.argv[2].replace('localhost', hostname);

var webdriver = require('selenium-webdriver')

var driver = new webdriver.Builder().
  withCapabilities({browserName: 'firefox'}).
  usingServer('http://localhost:2005/wd/hub').
  build();

driver.get(url).then(function() {
  console.log('foo');
});

setInterval(function() {
  console.log('bar');
}, 4000);

process.on('SIGTERM', function() {
  driver.quit();
});
